sylius_twig_hooks:
    hooks:
        'sylius_admin.common.index.content.grid':
            grid_assistant:
                template: '@GuiziwebSyliusGridAssistantPlugin/admin/grid/grid_assistant.html.twig'
                priority: 250
