services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $aiQueryLimiter: '@limiter.guiziweb_grid_assistant'

    Guiziweb\SyliusGridAssistantPlugin\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations}'

    Symfony\UX\Autocomplete\AutocompleterRegistry:
        alias: 'ux.autocomplete.autocompleter_registry'

    Guiziweb\SyliusGridAssistantPlugin\Processor\GridQueryProcessor:
        arguments:
            $model: '%guiziweb.grid_assistant.model%'

    Guiziweb\SyliusGridAssistantPlugin\Twig\Component\GridAssistantComponent:
        tags:
            - { name: 'sylius.live_component.admin', key: 'guiziweb:grid_assistant:search', template: '@GuiziwebSyliusGridAssistantPlugin/components/grid_assistant.html.twig' }